/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Sistema_de_proveedores;

import Clases.Cliente;
import Clases.Producto;
import static Menu.Menu_Principal.clientes;
import static Menu.Menu_Principal.productos;
import Utilidades.Cantidad_Productos;
import java.awt.event.KeyEvent;
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.RowSorter;
import javax.swing.SortOrder;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import java.util.Calendar;
/**
 *
 * @author José Manuel Carrillo Torres
 */
public class Sis_Proveedores_Productos extends javax.swing.JFrame {

    DefaultTableModel dfm_EntradaProducto;
    public static DefaultTableModel dfm_SalidaProducto_Inventario; 
    public static DefaultTableModel dfm_SalidaProducto_Venta; 
    DefaultTableModel dfm_ConsultasProducto;
    
    public static int row_inventario=-1;
    
    int numclte=1;
    int nuevo_cliente=1;
    /**
     * Creates new form FormProductos
     */
    public Sis_Proveedores_Productos() {
        initComponents();
        
        this.setLocationRelativeTo(null);
        this.dfm_EntradaProducto = (DefaultTableModel) jTable_EntradaProducto.getModel();
        this.dfm_ConsultasProducto = (DefaultTableModel) jTable_ConsultasProducto.getModel();
        this.dfm_SalidaProducto_Inventario = (DefaultTableModel) jTable_SalidaProducto_Inventario.getModel();
        this.dfm_SalidaProducto_Venta = (DefaultTableModel) jTable_SalidaProducto_Venta.getModel();
        Nuevo_Cliente();
        jLabel14.setText("Cliente del día: "+nuevo_cliente);
        VistaParaGerente(Menu.Iniciando_Sistema.gerente);   
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel_EntradaProducto = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable_EntradaProducto = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField_EntradaProducto_EntradasProducto = new javax.swing.JTextField();
        jButton_EntradaProducto_AgregarEntrada = new javax.swing.JButton();
        jTextField_EntradaProducto_NombreProducto = new javax.swing.JTextField();
        jPanel_SalidaProducto = new javax.swing.JPanel();
        jPanel_SalidaProducto1 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jTextField_SalidaProducto_Total = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jButton_SalidaProducto_Vender = new javax.swing.JButton();
        jButton_SalidaProducto_LimpiarTodo = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTable_SalidaProducto_Inventario = new javax.swing.JTable();
        jScrollPane9 = new javax.swing.JScrollPane();
        jTable_SalidaProducto_Venta = new javax.swing.JTable();
        jTextField_SalidaProducto_NombreProducto = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jPanel_ConsultasProducto = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_ConsultasProducto = new javax.swing.JTable();
        jComboBox_ConsultasProducto_SeleccionarCriterio = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jTextField_ConsultasProducto_ValorCriterio = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jCheckBox_ConsultasProducto_Descendente = new javax.swing.JCheckBox();
        jButton_ConsultasProducto_Consultar = new javax.swing.JButton();
        jButton_ConsultasProducto_LimpiarTabla = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton_AbrirModuloProveedores = new javax.swing.JButton();
        jButton_AbrirMenuPrincipal = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Módulo de productos");

        jPanel_EntradaProducto.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                jPanel_EntradaProductoComponentHidden(evt);
            }
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jPanel_EntradaProductoComponentShown(evt);
            }
        });

        jTable_EntradaProducto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Número de producto", "Nombre", "Contenido", "Linea", "Existencia", "Precio"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable_EntradaProducto.setEnabled(false);
        jTable_EntradaProducto.getTableHeader().setReorderingAllowed(false);
        jScrollPane4.setViewportView(jTable_EntradaProducto);

        jLabel6.setText("Escriba la cantidad de unidades que entrarán a las existencias: ");

        jLabel7.setText("Escriba el nombre del producto y haga clic en la fila del producto:");

        jTextField_EntradaProducto_EntradasProducto.setEnabled(false);
        jTextField_EntradaProducto_EntradasProducto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_EntradaProducto_EntradasProductoKeyTyped(evt);
            }
        });

        jButton_EntradaProducto_AgregarEntrada.setText("Agregar entrada");
        jButton_EntradaProducto_AgregarEntrada.setEnabled(false);
        jButton_EntradaProducto_AgregarEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_EntradaProducto_AgregarEntradaActionPerformed(evt);
            }
        });

        jTextField_EntradaProducto_NombreProducto.setEnabled(false);
        jTextField_EntradaProducto_NombreProducto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_EntradaProducto_NombreProductoKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel_EntradaProductoLayout = new javax.swing.GroupLayout(jPanel_EntradaProducto);
        jPanel_EntradaProducto.setLayout(jPanel_EntradaProductoLayout);
        jPanel_EntradaProductoLayout.setHorizontalGroup(
            jPanel_EntradaProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_EntradaProductoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_EntradaProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 755, Short.MAX_VALUE)
                    .addGroup(jPanel_EntradaProductoLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField_EntradaProducto_NombreProducto))
                    .addGroup(jPanel_EntradaProductoLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_EntradaProducto_EntradasProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton_EntradaProducto_AgregarEntrada)))
                .addContainerGap())
        );
        jPanel_EntradaProductoLayout.setVerticalGroup(
            jPanel_EntradaProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_EntradaProductoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_EntradaProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextField_EntradaProducto_NombreProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 404, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_EntradaProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField_EntradaProducto_EntradasProducto)
                    .addGroup(jPanel_EntradaProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(jButton_EntradaProducto_AgregarEntrada)))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Entrada producto", jPanel_EntradaProducto);

        jPanel_SalidaProducto.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                jPanel_SalidaProductoComponentHidden(evt);
            }
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jPanel_SalidaProductoComponentShown(evt);
            }
        });

        jPanel_SalidaProducto1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                jPanel_SalidaProducto1ComponentHidden(evt);
            }
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jPanel_SalidaProducto1ComponentShown(evt);
            }
        });

        jLabel14.setText("Cliente del día: - -");

        jLabel15.setText("Escriba el nombre del producto y haga clic en la fila del producto para agregarlo a la lista:");

        jLabel16.setText("Lista de productos a vender");

        jTextField_SalidaProducto_Total.setEditable(false);
        jTextField_SalidaProducto_Total.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        jTextField_SalidaProducto_Total.setText("$ 00.00");

        jLabel17.setText("Total de la venta:");

        jButton_SalidaProducto_Vender.setText("Vender");
        jButton_SalidaProducto_Vender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_SalidaProducto_VenderActionPerformed(evt);
            }
        });

        jButton_SalidaProducto_LimpiarTodo.setText("Limpiar lista");
        jButton_SalidaProducto_LimpiarTodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_SalidaProducto_LimpiarTodoActionPerformed(evt);
            }
        });

        jTable_SalidaProducto_Inventario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Contenido", "Precio"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable_SalidaProducto_Inventario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_SalidaProducto_InventarioMouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(jTable_SalidaProducto_Inventario);

        jTable_SalidaProducto_Venta.setBorder(new javax.swing.border.MatteBorder(null));
        jTable_SalidaProducto_Venta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Contenido", "Precio", "Cantidad", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable_SalidaProducto_Venta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_SalidaProducto_VentaMouseClicked(evt);
            }
        });
        jScrollPane9.setViewportView(jTable_SalidaProducto_Venta);

        jTextField_SalidaProducto_NombreProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField_SalidaProducto_NombreProductoMouseClicked(evt);
            }
        });
        jTextField_SalidaProducto_NombreProducto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_SalidaProducto_NombreProductoKeyTyped(evt);
            }
        });

        jLabel8.setText("Clic en un producto para removerlo");

        javax.swing.GroupLayout jPanel_SalidaProducto1Layout = new javax.swing.GroupLayout(jPanel_SalidaProducto1);
        jPanel_SalidaProducto1.setLayout(jPanel_SalidaProducto1Layout);
        jPanel_SalidaProducto1Layout.setHorizontalGroup(
            jPanel_SalidaProducto1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_SalidaProducto1Layout.createSequentialGroup()
                .addGroup(jPanel_SalidaProducto1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_SalidaProducto1Layout.createSequentialGroup()
                        .addGap(284, 284, 284)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel_SalidaProducto1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane9, javax.swing.GroupLayout.DEFAULT_SIZE, 755, Short.MAX_VALUE))
                    .addGroup(jPanel_SalidaProducto1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel_SalidaProducto1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel_SalidaProducto1Layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel8))
                            .addGroup(jPanel_SalidaProducto1Layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField_SalidaProducto_NombreProducto))))
                    .addGroup(jPanel_SalidaProducto1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane6))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_SalidaProducto1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton_SalidaProducto_LimpiarTodo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel14)
                        .addGap(120, 120, 120)
                        .addGroup(jPanel_SalidaProducto1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton_SalidaProducto_Vender, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_SalidaProducto1Layout.createSequentialGroup()
                                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField_SalidaProducto_Total, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        jPanel_SalidaProducto1Layout.setVerticalGroup(
            jPanel_SalidaProducto1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_SalidaProducto1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_SalidaProducto1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jTextField_SalidaProducto_NombreProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_SalidaProducto1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane9, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_SalidaProducto1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_SalidaProducto_Total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(jLabel14)
                    .addComponent(jButton_SalidaProducto_LimpiarTodo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton_SalidaProducto_Vender)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel_SalidaProductoLayout = new javax.swing.GroupLayout(jPanel_SalidaProducto);
        jPanel_SalidaProducto.setLayout(jPanel_SalidaProductoLayout);
        jPanel_SalidaProductoLayout.setHorizontalGroup(
            jPanel_SalidaProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_SalidaProductoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel_SalidaProducto1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel_SalidaProductoLayout.setVerticalGroup(
            jPanel_SalidaProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_SalidaProductoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel_SalidaProducto1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Salida producto", jPanel_SalidaProducto);

        jPanel_ConsultasProducto.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                jPanel_ConsultasProductoComponentHidden(evt);
            }
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jPanel_ConsultasProductoComponentShown(evt);
            }
        });

        jTable_ConsultasProducto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Número de producto", "Nombre", "Contenido", "Linea", "Existencia", "Precio"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable_ConsultasProducto);

        jComboBox_ConsultasProducto_SeleccionarCriterio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todo el inventario", "Por número", "Por nombre", "Por contenido", "Por linea", "Por existencias" }));
        jComboBox_ConsultasProducto_SeleccionarCriterio.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox_ConsultasProducto_SeleccionarCriterioItemStateChanged(evt);
            }
        });

        jLabel2.setText("Seleccione el criterio de consulta:");

        jTextField_ConsultasProducto_ValorCriterio.setEnabled(false);

        jLabel3.setText("Ingrese el valor del criterio:");

        jCheckBox_ConsultasProducto_Descendente.setText("Descendente");
        jCheckBox_ConsultasProducto_Descendente.setEnabled(false);

        jButton_ConsultasProducto_Consultar.setText("Consultar");
        jButton_ConsultasProducto_Consultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ConsultasProducto_ConsultarActionPerformed(evt);
            }
        });

        jButton_ConsultasProducto_LimpiarTabla.setText("Limpiar tabla");

        javax.swing.GroupLayout jPanel_ConsultasProductoLayout = new javax.swing.GroupLayout(jPanel_ConsultasProducto);
        jPanel_ConsultasProducto.setLayout(jPanel_ConsultasProductoLayout);
        jPanel_ConsultasProductoLayout.setHorizontalGroup(
            jPanel_ConsultasProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_ConsultasProductoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_ConsultasProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel_ConsultasProductoLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox_ConsultasProducto_SeleccionarCriterio, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_ConsultasProducto_ValorCriterio, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCheckBox_ConsultasProducto_Descendente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton_ConsultasProducto_Consultar, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_ConsultasProductoLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton_ConsultasProducto_LimpiarTabla)))
                .addContainerGap())
        );
        jPanel_ConsultasProductoLayout.setVerticalGroup(
            jPanel_ConsultasProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_ConsultasProductoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_ConsultasProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBox_ConsultasProducto_SeleccionarCriterio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField_ConsultasProducto_ValorCriterio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox_ConsultasProducto_Descendente)
                    .addComponent(jButton_ConsultasProducto_Consultar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 406, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton_ConsultasProducto_LimpiarTabla)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Consultas producto", jPanel_ConsultasProducto);

        jLabel1.setText("Elija una de las siguientes pestañas para realizar una operación con respecto a los productos:");

        jButton_AbrirModuloProveedores.setText("Abrir Módulo de proveedores");
        jButton_AbrirModuloProveedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_AbrirModuloProveedoresActionPerformed(evt);
            }
        });

        jButton_AbrirMenuPrincipal.setText("Abrir menú principal");
        jButton_AbrirMenuPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_AbrirMenuPrincipalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton_AbrirMenuPrincipal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton_AbrirModuloProveedores)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTabbedPane1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_AbrirModuloProveedores)
                    .addComponent(jButton_AbrirMenuPrincipal))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    void VistaParaGerente(boolean gerente){
        if(gerente){
           jTextField_EntradaProducto_NombreProducto.setEnabled(true);
           jTable_EntradaProducto.setEnabled(true);
           jTextField_EntradaProducto_EntradasProducto.setEnabled(true);
           jButton_EntradaProducto_AgregarEntrada.setEnabled(true);
        }    
    }
    
    void Nuevo_Cliente(){
        Calendar calendario = Calendar.getInstance();
        String dia=String.valueOf(calendario.get(Calendar.DAY_OF_MONTH));
        String mes=String.valueOf(calendario.get(Calendar.MONTH)+1);
        String año=String.valueOf(calendario.get(Calendar.YEAR));
        if(Integer.valueOf(dia)<10)
            dia="0"+dia;
        if(Integer.valueOf(mes)<10)
            mes="0"+mes;         
        String hoy=dia+"/"+mes+"/"+año;
        for(int i=0;i<clientes.size();i++){        
            if(clientes.get(i).getFecha().equals(hoy)){
                if(nuevo_cliente==clientes.get(i).getNumeroCliente())
                    nuevo_cliente++;
            } 
        }        
    }
    
    void ActualizarProductos(){
        try{
            FileWriter fw = new FileWriter("Productos.txt");
            BufferedWriter bw = new BufferedWriter(fw);
            PrintWriter pw = new PrintWriter(bw);
            int c=0;
            for(int j=0;j<productos.size();j++){
                if(c==0)
                    pw.write(productos.get(j).getNumero()+"|"+productos.get(j).getNombre()+"|"+productos.get(j).getContenido()+"|"+productos.get(j).getLinea()+"|"+productos.get(j).getExistencia()+"|"+productos.get(j).getPrecio());
                else
                    pw.append("\r\n"+productos.get(j).getNumero()+"|"+productos.get(j).getNombre()+"|"+productos.get(j).getContenido()+"|"+productos.get(j).getLinea()+"|"+productos.get(j).getExistencia()+"|"+productos.get(j).getPrecio());
                c++;
            }
            pw.close();
            bw.close();
            fw.close();
        }
        catch (IOException ex){}
    }
        
    void ActualizarClientes(){
        try{ 
            FileWriter fw = new FileWriter("Clientes.txt");
            BufferedWriter bw = new BufferedWriter(fw);
            PrintWriter pw = new PrintWriter(bw);
            int c=0;
            for(int j=0;j<clientes.size();j++){
                if(c==0)
                    pw.write(clientes.get(j).getNumeroCliente()+"|"+clientes.get(j).getNumeroProducto()+"|"+clientes.get(j).getCantidad()+"|"+clientes.get(j).getImporte()+"|"+clientes.get(j).getFecha());
                else
                    pw.append("\r\n"+clientes.get(j).getNumeroCliente()+"|"+clientes.get(j).getNumeroProducto()+"|"+clientes.get(j).getCantidad()+"|"+clientes.get(j).getImporte()+"|"+clientes.get(j).getFecha());
                c++;
            }
            pw.close();
            bw.close();
            fw.close();
        }
        catch (IOException ex){}
    }
    
    private void jButton_AbrirModuloProveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_AbrirModuloProveedoresActionPerformed
        while(dfm_ConsultasProducto.getRowCount() > 0){dfm_ConsultasProducto.removeRow(0);}
        while(dfm_SalidaProducto_Venta.getRowCount() > 0){dfm_SalidaProducto_Venta.removeRow(0);}
        while(dfm_SalidaProducto_Inventario.getRowCount() > 0){dfm_SalidaProducto_Inventario.removeRow(0);}
        while(dfm_EntradaProducto.getRowCount() > 0){dfm_EntradaProducto.removeRow(0);}
        row_inventario=-1;
        Sis_Proveedores_Proveedores fp = new Sis_Proveedores_Proveedores();
        this.dispose();
        fp.setVisible(true);
    }//GEN-LAST:event_jButton_AbrirModuloProveedoresActionPerformed

    private void jButton_EntradaProducto_AgregarEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_EntradaProducto_AgregarEntradaActionPerformed
        int r = jTable_EntradaProducto.getSelectedRow(); 
        if(r<0)
            JOptionPane.showMessageDialog(null, "Seleccione la fila con la información del producto", "Atención",JOptionPane.WARNING_MESSAGE);
        else{
            if(jTextField_EntradaProducto_EntradasProducto.getText().equals("")){
                JOptionPane.showMessageDialog(null, "Escriba la cantidad de entradas del producto", "Atención",JOptionPane.WARNING_MESSAGE);
            }
            else{
                String cantidad_s=jTextField_EntradaProducto_EntradasProducto.getText();
                int longitud=cantidad_s.length();
                if(longitud>=5){
                    JOptionPane.showMessageDialog(null, "Ingrese una cantidad con menos de 5 digitos","Atención",JOptionPane.WARNING_MESSAGE); 
                }
                else{
                    int entradas=Integer.parseInt(jTextField_EntradaProducto_EntradasProducto.getText());
                    int opcion = JOptionPane.showConfirmDialog(null, "¿Agregar "+entradas+" entrada(s)?", "Confirmar entradas", JOptionPane.YES_NO_OPTION);
                    if(opcion==0){
                        int num=Integer.parseInt(dfm_EntradaProducto.getValueAt(r,0).toString());                   
                        for(Producto p :productos){
                            if(entradas<0){
                                JOptionPane.showMessageDialog(null, "Por favor escriba valores positivos", "Atención",JOptionPane.WARNING_MESSAGE); 
                            }
                            else{
                                if(p.getNumero()==num){
                                    p.setExistencia(p.getExistencia()+entradas);
                                    dfm_EntradaProducto.setValueAt(p.getExistencia(), r, 4);
                                    JOptionPane.showMessageDialog(null, "El inventario ha sido actualizado exitósamente", "Información",JOptionPane.INFORMATION_MESSAGE); 
                                }
                            }
                        }   
                        jTextField_EntradaProducto_EntradasProducto.setText(null);  
                    }
                }
            }
        }  
        ActualizarProductos();      
    }//GEN-LAST:event_jButton_EntradaProducto_AgregarEntradaActionPerformed

    private void jButton_AbrirMenuPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_AbrirMenuPrincipalActionPerformed
        while(dfm_ConsultasProducto.getRowCount() > 0){dfm_ConsultasProducto.removeRow(0);}
        while(dfm_SalidaProducto_Venta.getRowCount() > 0){dfm_SalidaProducto_Venta.removeRow(0);}
        while(dfm_SalidaProducto_Inventario.getRowCount() > 0){dfm_SalidaProducto_Inventario.removeRow(0);}
        while(dfm_EntradaProducto.getRowCount() > 0){dfm_EntradaProducto.removeRow(0);}
        row_inventario=-1;
        Menu.Menu_Principal mi = new Menu.Menu_Principal();
        this.dispose();
        mi.setVisible(true);
    }//GEN-LAST:event_jButton_AbrirMenuPrincipalActionPerformed

    private void jTextField_EntradaProducto_NombreProductoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_EntradaProducto_NombreProductoKeyTyped
        while(dfm_EntradaProducto.getRowCount() > 0){dfm_EntradaProducto.removeRow(0);}
        String s = jTextField_EntradaProducto_NombreProducto.getText();
        for(Producto p: productos){
            if(p.getNombre().toLowerCase().contains(s.toLowerCase()))
                dfm_EntradaProducto.addRow(new Object[]{p.getNumero(),p.getNombre(),p.getContenido(),p.getLinea(),p.getExistencia(),p.getPrecio()});
        }
        if(dfm_EntradaProducto.getRowCount()==1){
            jTable_EntradaProducto.setRowSelectionInterval(0,0);
        }
    }//GEN-LAST:event_jTextField_EntradaProducto_NombreProductoKeyTyped

    private void jPanel_EntradaProductoComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jPanel_EntradaProductoComponentShown
        for(Producto p: productos){
                dfm_EntradaProducto.addRow(new Object[]{p.getNumero(),p.getNombre(),p.getContenido(),p.getLinea(),p.getExistencia(),p.getPrecio()});
        }
    }//GEN-LAST:event_jPanel_EntradaProductoComponentShown

    private void jPanel_EntradaProductoComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jPanel_EntradaProductoComponentHidden
        while(dfm_EntradaProducto.getRowCount() > 0){dfm_EntradaProducto.removeRow(0);}
    }//GEN-LAST:event_jPanel_EntradaProductoComponentHidden

    private void jButton_ConsultasProducto_ConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ConsultasProducto_ConsultarActionPerformed
        while(dfm_ConsultasProducto.getRowCount() > 0){dfm_ConsultasProducto.removeRow(0);}
        switch (jComboBox_ConsultasProducto_SeleccionarCriterio.getSelectedIndex()) {
            case 1:
                for(Producto p:productos){
                    if(!jTextField_ConsultasProducto_ValorCriterio.getText().equals("")){
                        if(p.getNumero()==Integer.parseInt(jTextField_ConsultasProducto_ValorCriterio.getText()))         
                            dfm_ConsultasProducto.addRow(new Object[]{p.getNumero(),p.getNombre(),p.getContenido(),p.getLinea(),p.getExistencia(),p.getPrecio()});
                    }
                    else
                        dfm_ConsultasProducto.addRow(new Object[]{p.getNumero(),p.getNombre(),p.getContenido(),p.getLinea(),p.getExistencia(),p.getPrecio()});
                }   if(jCheckBox_ConsultasProducto_Descendente.isSelected()){
                    TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>(dfm_ConsultasProducto);
                    List<RowSorter.SortKey> sortKeys = new ArrayList<>();
                    sortKeys.add(new RowSorter.SortKey(0, SortOrder.DESCENDING));
                    sorter.setSortKeys(sortKeys);
                    jTable_ConsultasProducto.setRowSorter(sorter);
                }
                else{
                    TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>(dfm_ConsultasProducto);
                    List<RowSorter.SortKey> sortKeys = new ArrayList<>();
                    sortKeys.add(new RowSorter.SortKey(0, SortOrder.ASCENDING));
                    sorter.setSortKeys(sortKeys);
                    jTable_ConsultasProducto.setRowSorter(sorter);
                }   break;
            case 2:
                for(Producto p:productos){
                    if(!jTextField_ConsultasProducto_ValorCriterio.getText().equals("")){
                        if(p.getNombre().toUpperCase().contains(jTextField_ConsultasProducto_ValorCriterio.getText().toUpperCase()))
                            dfm_ConsultasProducto.addRow(new Object[]{p.getNumero(),p.getNombre(),p.getContenido(),p.getLinea(),p.getExistencia(),p.getPrecio()});
                    }
                    else
                        dfm_ConsultasProducto.addRow(new Object[]{p.getNumero(),p.getNombre(),p.getContenido(),p.getLinea(),p.getExistencia(),p.getPrecio()});
                }   if(jCheckBox_ConsultasProducto_Descendente.isSelected()){
                    TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>(dfm_ConsultasProducto);
                    List<RowSorter.SortKey> sortKeys = new ArrayList<>();
                    sortKeys.add(new RowSorter.SortKey(1, SortOrder.DESCENDING));
                    sorter.setSortKeys(sortKeys);
                    jTable_ConsultasProducto.setRowSorter(sorter);         
                }
                else{
                    TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>(dfm_ConsultasProducto);
                    List<RowSorter.SortKey> sortKeys = new ArrayList<>();
                    sortKeys.add(new RowSorter.SortKey(1, SortOrder.ASCENDING));
                    sorter.setSortKeys(sortKeys);
                    jTable_ConsultasProducto.setRowSorter(sorter);
                }   break;
            case 3:
                for(Producto p:productos){
                    if(p.getContenido().toUpperCase().contains(jTextField_ConsultasProducto_ValorCriterio.getText().toUpperCase()))
                        dfm_ConsultasProducto.addRow(new Object[]{p.getNumero(),p.getNombre(),p.getContenido(),p.getLinea(),p.getExistencia(),p.getPrecio()});
                }   break;
            case 4:
                for(Producto p:productos){
                    if(p.getLinea().toUpperCase().contains(jTextField_ConsultasProducto_ValorCriterio.getText().toUpperCase()))
                        dfm_ConsultasProducto.addRow(new Object[]{p.getNumero(),p.getNombre(),p.getContenido(),p.getLinea(),p.getExistencia(),p.getPrecio()});
                }   break;
            case 5:
                for(Producto p:productos){
                    if(p.getExistencia()==Integer.parseInt(jTextField_ConsultasProducto_ValorCriterio.getText()))
                        dfm_ConsultasProducto.addRow(new Object[]{p.getNumero(),p.getNombre(),p.getContenido(),p.getLinea(),p.getExistencia(),p.getPrecio()});
                }   break;
            default:
                for(Producto p:productos){
                    dfm_ConsultasProducto.addRow(new Object[]{p.getNumero(),p.getNombre(),p.getContenido(),p.getLinea(),p.getExistencia(),p.getPrecio()});
                }   break;
        }
    }//GEN-LAST:event_jButton_ConsultasProducto_ConsultarActionPerformed

    private void jPanel_SalidaProductoComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jPanel_SalidaProductoComponentShown
        for(Producto p: productos){
            if(p.getExistencia()>0)
            dfm_SalidaProducto_Inventario.addRow(new Object[]{p.getNombre(),p.getContenido(),p.getPrecio()});
        }
    }//GEN-LAST:event_jPanel_SalidaProductoComponentShown

    private void jPanel_SalidaProductoComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jPanel_SalidaProductoComponentHidden
        while(dfm_SalidaProducto_Inventario.getRowCount() > 0){dfm_SalidaProducto_Inventario.removeRow(0);}
    }//GEN-LAST:event_jPanel_SalidaProductoComponentHidden

    private void jButton_SalidaProducto_VenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_SalidaProducto_VenderActionPerformed
        if(jTable_SalidaProducto_Venta.getRowCount()>0){
            int opcion = JOptionPane.showConfirmDialog(null, "¿Proceder con la venta?", "Confirmar venta", JOptionPane.YES_NO_OPTION);
            if(opcion==0){
                Calendar calendario = Calendar.getInstance();
                String dia=String.valueOf(calendario.get(Calendar.DAY_OF_MONTH));
                String mes=String.valueOf(calendario.get(Calendar.MONTH)+1);
                String año=String.valueOf(calendario.get(Calendar.YEAR));       
                if(Integer.valueOf(dia)<10)
                    dia="0"+dia;
                if(Integer.valueOf(mes)<10)
                    mes="0"+mes;         
                String fecha=dia+"/"+mes+"/"+año;
                String prods="";
                for(int i=0;i<dfm_SalidaProducto_Venta.getRowCount();i++){
                    int cantidad=Integer.parseInt(dfm_SalidaProducto_Venta.getValueAt(i, 3).toString());
                    float total = Float.valueOf(dfm_SalidaProducto_Venta.getValueAt(i, 4).toString());
                    int numero_producto=0;
                    for(Producto p :productos){
                        if(p.getNombre().equals(dfm_SalidaProducto_Venta.getValueAt(i, 0).toString())){
                            p.setExistencia(p.getExistencia()-cantidad);
                            numero_producto=p.getNumero();
                        }                   
                    }
                    Cliente c = new Cliente(nuevo_cliente, numero_producto, cantidad, total, fecha);
                    clientes.add(c);               
                }    
                ActualizarClientes();
                ActualizarProductos();
                jTextField_SalidaProducto_Total.setText("$ 00.00");
                JOptionPane.showMessageDialog(null, "La venta se ha concretado con éxito","Información",JOptionPane.INFORMATION_MESSAGE); 
                Nuevo_Cliente();
                jLabel14.setText("Cliente del día: "+nuevo_cliente);
                while(dfm_SalidaProducto_Venta.getRowCount() > 0){dfm_SalidaProducto_Venta.removeRow(0);}
                while(dfm_SalidaProducto_Inventario.getRowCount() > 0){dfm_SalidaProducto_Inventario.removeRow(0);}
                for(Producto p: productos){
                    if(p.getExistencia()>0)
                        dfm_SalidaProducto_Inventario.addRow(new Object[]{p.getNombre(),p.getContenido(),p.getPrecio()});
                }  
            }                 
        } 
    }//GEN-LAST:event_jButton_SalidaProducto_VenderActionPerformed

    private void jButton_SalidaProducto_LimpiarTodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_SalidaProducto_LimpiarTodoActionPerformed
        jTextField_SalidaProducto_Total.setText("$ 00.00");
        while(dfm_SalidaProducto_Venta.getRowCount() > 0){dfm_SalidaProducto_Venta.removeRow(0);}
    }//GEN-LAST:event_jButton_SalidaProducto_LimpiarTodoActionPerformed

    private void jTable_SalidaProducto_InventarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_SalidaProducto_InventarioMouseClicked
        int r=jTable_SalidaProducto_Inventario.getSelectedRow();
        if(r>-1){
            row_inventario=jTable_SalidaProducto_Inventario.getSelectedRow();
            jTable_SalidaProducto_Inventario.setVisible(false);
            jButton_SalidaProducto_Vender.setEnabled(false);
            Cantidad_Productos fc = new Cantidad_Productos();
            fc.setAlwaysOnTop(true);
            fc.setVisible(true);   
        }   
    }//GEN-LAST:event_jTable_SalidaProducto_InventarioMouseClicked

    private void jTable_SalidaProducto_VentaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_SalidaProducto_VentaMouseClicked
        int j=jTable_SalidaProducto_Venta.getSelectedRow();
        if(j>-1)
        dfm_SalidaProducto_Venta.removeRow(j);
        double total=0;
        for(int i=0;i<dfm_SalidaProducto_Venta.getRowCount();i++){
            total+=Double.parseDouble(dfm_SalidaProducto_Venta.getValueAt(i,4).toString());
        }
        jTextField_SalidaProducto_Total.setText("$ "+String.valueOf(total));
    }//GEN-LAST:event_jTable_SalidaProducto_VentaMouseClicked

    private void jTextField_SalidaProducto_NombreProductoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_SalidaProducto_NombreProductoKeyTyped
        while(dfm_SalidaProducto_Inventario.getRowCount() > 0){dfm_SalidaProducto_Inventario.removeRow(0);}
        String s = jTextField_SalidaProducto_NombreProducto.getText();
        for(Producto p: productos){
            if(p.getNombre().toLowerCase().contains(s.toLowerCase()))
                dfm_SalidaProducto_Inventario.addRow(new Object[]{p.getNombre(),p.getContenido(),p.getPrecio()});
        }
        if(dfm_SalidaProducto_Inventario.getRowCount()==1){
            jTable_SalidaProducto_Inventario.setRowSelectionInterval(0,0);
            row_inventario=jTable_SalidaProducto_Inventario.getSelectedRow();
            Cantidad_Productos fc = new Cantidad_Productos();
            fc.setVisible(true); 
        }  
    }//GEN-LAST:event_jTextField_SalidaProducto_NombreProductoKeyTyped

    private void jPanel_SalidaProducto1ComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jPanel_SalidaProducto1ComponentHidden
        while(dfm_SalidaProducto_Inventario.getRowCount() > 0){dfm_SalidaProducto_Inventario.removeRow(0);}
    }//GEN-LAST:event_jPanel_SalidaProducto1ComponentHidden

    private void jPanel_SalidaProducto1ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jPanel_SalidaProducto1ComponentShown
        for(Producto p: productos){
            if(p.getExistencia()>0)
                dfm_SalidaProducto_Inventario.addRow(new Object[]{p.getNombre(),p.getContenido(),p.getPrecio()});
        }
    }//GEN-LAST:event_jPanel_SalidaProducto1ComponentShown

    private void jTextField_EntradaProducto_EntradasProductoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_EntradaProducto_EntradasProductoKeyTyped
         char vchar=evt.getKeyChar();
            if(!(Character.isDigit(vchar))||(vchar==KeyEvent.VK_BACK_SPACE)||(vchar==KeyEvent.VK_DELETE))
            evt.consume();
    }//GEN-LAST:event_jTextField_EntradaProducto_EntradasProductoKeyTyped

    private void jComboBox_ConsultasProducto_SeleccionarCriterioItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox_ConsultasProducto_SeleccionarCriterioItemStateChanged
        while(dfm_ConsultasProducto.getRowCount() > 0){dfm_ConsultasProducto.removeRow(0);}
        int index=jComboBox_ConsultasProducto_SeleccionarCriterio.getSelectedIndex();
        if(index==0){        
            jCheckBox_ConsultasProducto_Descendente.setEnabled(false);
            jButton_ConsultasProducto_Consultar.setEnabled(false);
            jTextField_ConsultasProducto_ValorCriterio.setEnabled(false);
            for(Producto p:productos){
                dfm_ConsultasProducto.addRow(new Object[]{p.getNumero(),p.getNombre(),p.getContenido(),p.getLinea(),p.getExistencia(),p.getPrecio()});
            }            
        }
        else if(index==3||index==4||index==5){
            jCheckBox_ConsultasProducto_Descendente.setEnabled(false);
            jButton_ConsultasProducto_Consultar.setEnabled(true);
            jTextField_ConsultasProducto_ValorCriterio.setEnabled(true);
        }
        else{
            jButton_ConsultasProducto_Consultar.setEnabled(true);
            jTextField_ConsultasProducto_ValorCriterio.setEnabled(true);
            jCheckBox_ConsultasProducto_Descendente.setEnabled(true);
        }
        jTextField_ConsultasProducto_ValorCriterio.setText("");
    }//GEN-LAST:event_jComboBox_ConsultasProducto_SeleccionarCriterioItemStateChanged

    private void jTextField_SalidaProducto_NombreProductoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField_SalidaProducto_NombreProductoMouseClicked
        jTextField_SalidaProducto_NombreProducto.setText("");
    }//GEN-LAST:event_jTextField_SalidaProducto_NombreProductoMouseClicked

    private void jPanel_ConsultasProductoComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jPanel_ConsultasProductoComponentShown
        for(Producto p: productos){
            dfm_ConsultasProducto.addRow(new Object[]{p.getNumero(),p.getNombre(),p.getContenido(),p.getLinea(),p.getExistencia(),p.getPrecio()});
        }  
    }//GEN-LAST:event_jPanel_ConsultasProductoComponentShown

    private void jPanel_ConsultasProductoComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jPanel_ConsultasProductoComponentHidden
        while(dfm_ConsultasProducto.getRowCount() > 0){dfm_ConsultasProducto.removeRow(0);}
    }//GEN-LAST:event_jPanel_ConsultasProductoComponentHidden

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sis_Proveedores_Productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sis_Proveedores_Productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sis_Proveedores_Productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sis_Proveedores_Productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sis_Proveedores_Productos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_AbrirMenuPrincipal;
    private javax.swing.JButton jButton_AbrirModuloProveedores;
    private javax.swing.JButton jButton_ConsultasProducto_Consultar;
    private javax.swing.JButton jButton_ConsultasProducto_LimpiarTabla;
    private javax.swing.JButton jButton_EntradaProducto_AgregarEntrada;
    private javax.swing.JButton jButton_SalidaProducto_LimpiarTodo;
    public static javax.swing.JButton jButton_SalidaProducto_Vender;
    private javax.swing.JCheckBox jCheckBox_ConsultasProducto_Descendente;
    private javax.swing.JComboBox<String> jComboBox_ConsultasProducto_SeleccionarCriterio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel_ConsultasProducto;
    private javax.swing.JPanel jPanel_EntradaProducto;
    private javax.swing.JPanel jPanel_SalidaProducto;
    private javax.swing.JPanel jPanel_SalidaProducto1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable_ConsultasProducto;
    private javax.swing.JTable jTable_EntradaProducto;
    public static javax.swing.JTable jTable_SalidaProducto_Inventario;
    public static javax.swing.JTable jTable_SalidaProducto_Venta;
    private javax.swing.JTextField jTextField_ConsultasProducto_ValorCriterio;
    private javax.swing.JTextField jTextField_EntradaProducto_EntradasProducto;
    private javax.swing.JTextField jTextField_EntradaProducto_NombreProducto;
    public static javax.swing.JTextField jTextField_SalidaProducto_NombreProducto;
    public static javax.swing.JTextField jTextField_SalidaProducto_Total;
    // End of variables declaration//GEN-END:variables

}
