/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Sistema_de_clientes;

import Clases.Cliente;
import Clases.Producto;
import static Menu.Menu_Principal.clientes;
import static Menu.Menu_Principal.productos;
import Utilidades.Cantidad_Productos;
import java.awt.event.KeyEvent;
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.RowSorter;
import javax.swing.SortOrder;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author José Manuel Carrillo Torres
 */
public class Sis_Clientes_Clientes extends javax.swing.JFrame {

    public static DefaultTableModel dfm_SalidaProducto_Inventario;
    public static DefaultTableModel dfm_SalidaProducto_Venta;
    DefaultTableModel dfm_ConsultaClientes; 
    
    public static int row_inventario=-1;
    
    int numclte=1;
    int nuevo_cliente=1;
    /**
     * Creates new form FormClientes
     */
    public Sis_Clientes_Clientes() {
        initComponents();
        this.setLocationRelativeTo(null);
        dfm_SalidaProducto_Inventario=(DefaultTableModel)jTable_RegistroClientes_Inventario.getModel();
        dfm_SalidaProducto_Venta=(DefaultTableModel)jTable_SalidaProducto_Venta.getModel();
        dfm_ConsultaClientes=(DefaultTableModel)jTable_ConsultaClientes.getModel();
        Nuevo_Cliente();
        jLabel14.setText("Cliente del día: "+nuevo_cliente);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel_ConsultaClientes = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable_ConsultaClientes = new javax.swing.JTable();
        jButton_ConsultaClientes_Consultar = new javax.swing.JButton();
        jCheckBox_ConsultaClientes_Descendente = new javax.swing.JCheckBox();
        jTextField_ConsultaClientes_Año = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField_ConsultaClientes_Mes = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField_ConsultaClientes_Dia = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jButton_ConsultaClientes_LimpiarTabla = new javax.swing.JButton();
        jPanel_SalidaProducto = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jTextField_SalidaProducto_Total = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jButton_RegistroClientes_Vender = new javax.swing.JButton();
        jButton_SalidaProducto_LimpiarTodo = new javax.swing.JButton();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTable_RegistroClientes_Inventario = new javax.swing.JTable();
        jScrollPane10 = new javax.swing.JScrollPane();
        jTable_SalidaProducto_Venta = new javax.swing.JTable();
        jTextField_SalidaProducto_NombreProducto = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jButton_AbrirMenuPrincipal = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Módulo de registro de ventas");

        jTable_ConsultaClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No. de cliente", "Producto", "Cantidad", "Importe"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable_ConsultaClientes.getTableHeader().setReorderingAllowed(false);
        jScrollPane4.setViewportView(jTable_ConsultaClientes);

        jButton_ConsultaClientes_Consultar.setText("Consultar");
        jButton_ConsultaClientes_Consultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ConsultaClientes_ConsultarActionPerformed(evt);
            }
        });

        jCheckBox_ConsultaClientes_Descendente.setText("Mostrar descendente");

        jTextField_ConsultaClientes_Año.setText("AAAA");
        jTextField_ConsultaClientes_Año.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField_ConsultaClientes_AñoFocusGained(evt);
            }
        });
        jTextField_ConsultaClientes_Año.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_ConsultaClientes_AñoKeyTyped(evt);
            }
        });

        jLabel8.setText("/");

        jTextField_ConsultaClientes_Mes.setText("MM");
        jTextField_ConsultaClientes_Mes.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField_ConsultaClientes_MesFocusGained(evt);
            }
        });
        jTextField_ConsultaClientes_Mes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_ConsultaClientes_MesKeyTyped(evt);
            }
        });

        jLabel9.setText("/");

        jTextField_ConsultaClientes_Dia.setText("DD");
        jTextField_ConsultaClientes_Dia.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField_ConsultaClientes_DiaFocusGained(evt);
            }
        });
        jTextField_ConsultaClientes_Dia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_ConsultaClientes_DiaKeyTyped(evt);
            }
        });

        jLabel10.setText("Indique una fecha válida:");

        jButton_ConsultaClientes_LimpiarTabla.setText("Limpiar tabla");
        jButton_ConsultaClientes_LimpiarTabla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ConsultaClientes_LimpiarTablaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_ConsultaClientesLayout = new javax.swing.GroupLayout(jPanel_ConsultaClientes);
        jPanel_ConsultaClientes.setLayout(jPanel_ConsultaClientesLayout);
        jPanel_ConsultaClientesLayout.setHorizontalGroup(
            jPanel_ConsultaClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_ConsultaClientesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_ConsultaClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 755, Short.MAX_VALUE)
                    .addGroup(jPanel_ConsultaClientesLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_ConsultaClientes_Dia, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_ConsultaClientes_Mes, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_ConsultaClientes_Año, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jCheckBox_ConsultaClientes_Descendente)
                        .addGap(18, 18, 18)
                        .addComponent(jButton_ConsultaClientes_Consultar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_ConsultaClientes_LimpiarTabla)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel_ConsultaClientesLayout.setVerticalGroup(
            jPanel_ConsultaClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_ConsultaClientesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_ConsultaClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jTextField_ConsultaClientes_Dia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jTextField_ConsultaClientes_Mes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jTextField_ConsultaClientes_Año, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox_ConsultaClientes_Descendente)
                    .addComponent(jButton_ConsultaClientes_Consultar)
                    .addComponent(jButton_ConsultaClientes_LimpiarTabla))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 465, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Consulta de clientes", jPanel_ConsultaClientes);

        jPanel_SalidaProducto.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                jPanel_SalidaProductoComponentHidden(evt);
            }
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jPanel_SalidaProductoComponentShown(evt);
            }
        });

        jLabel14.setText("Cliente del día: - -");

        jLabel15.setText("Escriba el nombre del producto y haga clic en la fila del producto para agregarlo a la lista:");

        jLabel16.setText("Lista de productos a vender");

        jTextField_SalidaProducto_Total.setEditable(false);
        jTextField_SalidaProducto_Total.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        jTextField_SalidaProducto_Total.setText("$ 00.00");

        jLabel17.setText("Total de la venta:");

        jButton_RegistroClientes_Vender.setText("Vender");
        jButton_RegistroClientes_Vender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_RegistroClientes_VenderActionPerformed(evt);
            }
        });

        jButton_SalidaProducto_LimpiarTodo.setText("Limpiar lista");
        jButton_SalidaProducto_LimpiarTodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_SalidaProducto_LimpiarTodoActionPerformed(evt);
            }
        });

        jTable_RegistroClientes_Inventario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Contenido", "Precio"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable_RegistroClientes_Inventario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_RegistroClientes_InventarioMouseClicked(evt);
            }
        });
        jScrollPane7.setViewportView(jTable_RegistroClientes_Inventario);

        jTable_SalidaProducto_Venta.setBorder(new javax.swing.border.MatteBorder(null));
        jTable_SalidaProducto_Venta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Contenido", "Precio", "Cantidad", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable_SalidaProducto_Venta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_SalidaProducto_VentaMouseClicked(evt);
            }
        });
        jScrollPane10.setViewportView(jTable_SalidaProducto_Venta);

        jTextField_SalidaProducto_NombreProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField_SalidaProducto_NombreProductoMouseClicked(evt);
            }
        });
        jTextField_SalidaProducto_NombreProducto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_SalidaProducto_NombreProductoKeyTyped(evt);
            }
        });

        jLabel11.setText("Clic en un producto para removerlo");

        javax.swing.GroupLayout jPanel_SalidaProductoLayout = new javax.swing.GroupLayout(jPanel_SalidaProducto);
        jPanel_SalidaProducto.setLayout(jPanel_SalidaProductoLayout);
        jPanel_SalidaProductoLayout.setHorizontalGroup(
            jPanel_SalidaProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_SalidaProductoLayout.createSequentialGroup()
                .addGroup(jPanel_SalidaProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_SalidaProductoLayout.createSequentialGroup()
                        .addGap(284, 284, 284)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel_SalidaProductoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane10, javax.swing.GroupLayout.DEFAULT_SIZE, 755, Short.MAX_VALUE))
                    .addGroup(jPanel_SalidaProductoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel_SalidaProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel_SalidaProductoLayout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel11))
                            .addGroup(jPanel_SalidaProductoLayout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField_SalidaProducto_NombreProducto))))
                    .addGroup(jPanel_SalidaProductoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane7))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_SalidaProductoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton_SalidaProducto_LimpiarTodo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel14)
                        .addGap(120, 120, 120)
                        .addGroup(jPanel_SalidaProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton_RegistroClientes_Vender, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_SalidaProductoLayout.createSequentialGroup()
                                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField_SalidaProducto_Total, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        jPanel_SalidaProductoLayout.setVerticalGroup(
            jPanel_SalidaProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_SalidaProductoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_SalidaProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jTextField_SalidaProducto_NombreProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_SalidaProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane10, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_SalidaProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_SalidaProducto_Total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(jLabel14)
                    .addComponent(jButton_SalidaProducto_LimpiarTodo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton_RegistroClientes_Vender, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Registro clientes", jPanel_SalidaProducto);

        jButton_AbrirMenuPrincipal.setText("Abrir menú principal");
        jButton_AbrirMenuPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_AbrirMenuPrincipalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton_AbrirMenuPrincipal)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton_AbrirMenuPrincipal)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    void Nuevo_Cliente(){
        Calendar calendario = Calendar.getInstance();
        String dia=String.valueOf(calendario.get(Calendar.DAY_OF_MONTH));
        String mes=String.valueOf(calendario.get(Calendar.MONTH)+1);
        String año=String.valueOf(calendario.get(Calendar.YEAR));
        if(Integer.valueOf(dia)<10)
            dia="0"+dia;
        if(Integer.valueOf(mes)<10)
            mes="0"+mes;         
        String hoy=dia+"/"+mes+"/"+año;
        for(int i=0;i<clientes.size();i++){        
            if(clientes.get(i).getFecha().equals(hoy)){
                if(nuevo_cliente==clientes.get(i).getNumeroCliente())
                    nuevo_cliente++;
            } 
        }        
    }
    
    void ActualizarClientes(){
        try{ 
            FileWriter fw = new FileWriter("Clientes.txt");
            BufferedWriter bw = new BufferedWriter(fw);
            PrintWriter pw = new PrintWriter(bw);
            int c=0;
            for(int j=0;j<clientes.size();j++){
                if(c==0)
                    pw.write(clientes.get(j).getNumeroCliente()+"|"+clientes.get(j).getNumeroProducto()+"|"+clientes.get(j).getCantidad()+"|"+clientes.get(j).getImporte()+"|"+clientes.get(j).getFecha());
                else
                    pw.append("\r\n"+clientes.get(j).getNumeroCliente()+"|"+clientes.get(j).getNumeroProducto()+"|"+clientes.get(j).getCantidad()+"|"+clientes.get(j).getImporte()+"|"+clientes.get(j).getFecha());
                c++;
            }
            pw.close();
            bw.close();
            fw.close();
        }
        catch (IOException ex){}
    }
    
    void ActualizarProductos(){
        try{
            FileWriter fw = new FileWriter("Productos.txt");
            BufferedWriter bw = new BufferedWriter(fw);
            PrintWriter pw = new PrintWriter(bw);
            int c=0;
            for(int j=0;j<productos.size();j++){
                if(c==0)
                    pw.write(productos.get(j).getNumero()+"|"+productos.get(j).getNombre()+"|"+productos.get(j).getContenido()+"|"+productos.get(j).getLinea()+"|"+productos.get(j).getExistencia()+"|"+productos.get(j).getPrecio());
                else
                    pw.append("\r\n"+productos.get(j).getNumero()+"|"+productos.get(j).getNombre()+"|"+productos.get(j).getContenido()+"|"+productos.get(j).getLinea()+"|"+productos.get(j).getExistencia()+"|"+productos.get(j).getPrecio());
                c++;
            }
            pw.close();
            bw.close();
            fw.close();
        }
        catch (IOException ex){}
    }
    
    private void jButton_AbrirMenuPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_AbrirMenuPrincipalActionPerformed
        row_inventario=-1;
        Menu.Menu_Principal mi = new Menu.Menu_Principal();
        this.dispose();
        mi.setVisible(true);
    }//GEN-LAST:event_jButton_AbrirMenuPrincipalActionPerformed

    private void jButton_ConsultaClientes_ConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ConsultaClientes_ConsultarActionPerformed
        while(dfm_ConsultaClientes.getRowCount() > 0){dfm_ConsultaClientes.removeRow(0);}
        String dia=jTextField_ConsultaClientes_Dia.getText();
        if(dia.length()<2)
            dia="0"+dia;
        String mes=jTextField_ConsultaClientes_Mes.getText();
        if (mes.length()<2)
            mes="0"+mes;
        String fecha=dia+"/"+mes+"/"+jTextField_ConsultaClientes_Año.getText();
        for(Cliente c:clientes){
            if(c.getFecha().equals(fecha)){
                dfm_ConsultaClientes.addRow(new Object[]{c.getNumeroCliente(),null,c.getCantidad(),c.getImporte()});
                for(Producto p:productos){
                    if(p.getNumero()==c.getNumeroProducto())
                        dfm_ConsultaClientes.setValueAt(p.getNombre(),dfm_ConsultaClientes.getRowCount()-1,1);
                }
            }
        }
        if(jCheckBox_ConsultaClientes_Descendente.isSelected()){
            TableRowSorter<TableModel> sorter = new TableRowSorter<>(jTable_ConsultaClientes.getModel());             
            List<RowSorter.SortKey> sortKeys = new ArrayList<>();
            sortKeys.add(new RowSorter.SortKey(0, SortOrder.DESCENDING));
            sorter.setSortKeys(sortKeys);
            jTable_ConsultaClientes.setRowSorter(sorter);
        }
        else{
            TableRowSorter<TableModel> sorter = new TableRowSorter<>(jTable_ConsultaClientes.getModel());
            List<RowSorter.SortKey> sortKeys = new ArrayList<>();
            sortKeys.add(new RowSorter.SortKey(0, SortOrder.ASCENDING));
            sorter.setSortKeys(sortKeys);
            jTable_ConsultaClientes.setRowSorter(sorter);
        }
        if(jTable_ConsultaClientes.getRowCount()==0)
            JOptionPane.showMessageDialog(null, "No existen registros sobre esta fecha","Atención",JOptionPane.WARNING_MESSAGE); 
    }//GEN-LAST:event_jButton_ConsultaClientes_ConsultarActionPerformed

    private void jButton_ConsultaClientes_LimpiarTablaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ConsultaClientes_LimpiarTablaActionPerformed
        while(dfm_ConsultaClientes.getRowCount() > 0){dfm_ConsultaClientes.removeRow(0);}
    }//GEN-LAST:event_jButton_ConsultaClientes_LimpiarTablaActionPerformed

    private void jTextField_ConsultaClientes_DiaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_ConsultaClientes_DiaFocusGained
        jTextField_ConsultaClientes_Dia.setText(null);
    }//GEN-LAST:event_jTextField_ConsultaClientes_DiaFocusGained

    private void jTextField_ConsultaClientes_MesFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_ConsultaClientes_MesFocusGained
        jTextField_ConsultaClientes_Mes.setText(null);
    }//GEN-LAST:event_jTextField_ConsultaClientes_MesFocusGained

    private void jTextField_ConsultaClientes_AñoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_ConsultaClientes_AñoFocusGained
        jTextField_ConsultaClientes_Año.setText(null);
    }//GEN-LAST:event_jTextField_ConsultaClientes_AñoFocusGained

    private void jButton_RegistroClientes_VenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_RegistroClientes_VenderActionPerformed
        if(jTable_SalidaProducto_Venta.getRowCount()>0){
            int opcion = JOptionPane.showConfirmDialog(null, "¿Proceder con la venta?", "Confirmar venta", JOptionPane.YES_NO_OPTION);
            if(opcion==0){
                Calendar calendario = Calendar.getInstance();
                String dia=String.valueOf(calendario.get(Calendar.DAY_OF_MONTH));
                String mes=String.valueOf(calendario.get(Calendar.MONTH)+1);
                String año=String.valueOf(calendario.get(Calendar.YEAR));       
                if(Integer.valueOf(dia)<10)
                    dia="0"+dia;
                if(Integer.valueOf(mes)<10)
                    mes="0"+mes;         
                String fecha=dia+"/"+mes+"/"+año;
                String prods="";
                for(int i=0;i<dfm_SalidaProducto_Venta.getRowCount();i++){
                    int cantidad=Integer.parseInt(dfm_SalidaProducto_Venta.getValueAt(i, 3).toString());
                    float total = Float.valueOf(dfm_SalidaProducto_Venta.getValueAt(i, 4).toString());
                    int numero_producto=0;
                    for(Producto p :productos){
                        if(p.getNombre().equals(dfm_SalidaProducto_Venta.getValueAt(i, 0).toString())){
                            p.setExistencia(p.getExistencia()-cantidad);
                            numero_producto=p.getNumero();
                        }                   
                    }
                    Cliente c = new Cliente(nuevo_cliente, numero_producto, cantidad, total, fecha);
                    clientes.add(c);               
                }        
                ActualizarClientes();
                ActualizarProductos();
                jTextField_SalidaProducto_Total.setText("$ 00.00");
                JOptionPane.showMessageDialog(null, "La venta se ha concretado con éxito","Información",JOptionPane.INFORMATION_MESSAGE); 
                Nuevo_Cliente();
                jLabel14.setText("Cliente del día: "+nuevo_cliente);
                while(dfm_SalidaProducto_Venta.getRowCount() > 0){dfm_SalidaProducto_Venta.removeRow(0);}
                while(dfm_SalidaProducto_Inventario.getRowCount() > 0){dfm_SalidaProducto_Inventario.removeRow(0);}
                for(Producto p: productos){
                    if(p.getExistencia()>0)
                        dfm_SalidaProducto_Inventario.addRow(new Object[]{p.getNombre(),p.getContenido(),p.getPrecio()});
                }  
            }                 
        } 
    }//GEN-LAST:event_jButton_RegistroClientes_VenderActionPerformed

    private void jButton_SalidaProducto_LimpiarTodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_SalidaProducto_LimpiarTodoActionPerformed
        jTextField_SalidaProducto_Total.setText("$ 00.00");
        while(dfm_SalidaProducto_Venta.getRowCount() > 0){dfm_SalidaProducto_Venta.removeRow(0);}
    }//GEN-LAST:event_jButton_SalidaProducto_LimpiarTodoActionPerformed

    private void jTable_RegistroClientes_InventarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_RegistroClientes_InventarioMouseClicked
        int r=jTable_RegistroClientes_Inventario.getSelectedRow();
        if(r>-1){
            row_inventario=jTable_RegistroClientes_Inventario.getSelectedRow();
            jTable_RegistroClientes_Inventario.setVisible(false);
            jButton_RegistroClientes_Vender.setEnabled(false);
            Cantidad_Productos fc = new Cantidad_Productos();
            fc.setAlwaysOnTop(true);
            fc.setVisible(true);
        }   
    }//GEN-LAST:event_jTable_RegistroClientes_InventarioMouseClicked

    private void jTable_SalidaProducto_VentaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_SalidaProducto_VentaMouseClicked
        int j=jTable_SalidaProducto_Venta.getSelectedRow();
        if(j>-1)
        dfm_SalidaProducto_Venta.removeRow(j);
        double total=0;
        for(int i=0;i<dfm_SalidaProducto_Venta.getRowCount();i++){
            total+=Double.parseDouble(dfm_SalidaProducto_Venta.getValueAt(i,4).toString());
        }
        jTextField_SalidaProducto_Total.setText("$ "+String.valueOf(total));
    }//GEN-LAST:event_jTable_SalidaProducto_VentaMouseClicked

    private void jTextField_SalidaProducto_NombreProductoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_SalidaProducto_NombreProductoKeyTyped
        while(dfm_SalidaProducto_Inventario.getRowCount() > 0){dfm_SalidaProducto_Inventario.removeRow(0);}
        String s = jTextField_SalidaProducto_NombreProducto.getText();
        for(Producto p: productos){
            if(p.getNombre().toLowerCase().contains(s.toLowerCase()))
            dfm_SalidaProducto_Inventario.addRow(new Object[]{p.getNombre(),p.getContenido(),p.getPrecio()});
        }
        if(dfm_SalidaProducto_Inventario.getRowCount()==1){
            jTable_RegistroClientes_Inventario.setRowSelectionInterval(0,0);
            row_inventario=jTable_RegistroClientes_Inventario.getSelectedRow();
            Cantidad_Productos fc = new Cantidad_Productos();
            fc.setVisible(true); 
        }  
    }//GEN-LAST:event_jTextField_SalidaProducto_NombreProductoKeyTyped

    private void jPanel_SalidaProductoComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jPanel_SalidaProductoComponentHidden
        while(dfm_SalidaProducto_Inventario.getRowCount() > 0){dfm_SalidaProducto_Inventario.removeRow(0);}
    }//GEN-LAST:event_jPanel_SalidaProductoComponentHidden

    private void jPanel_SalidaProductoComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jPanel_SalidaProductoComponentShown
        for(Producto p: productos){
            if(p.getExistencia()>0)
            dfm_SalidaProducto_Inventario.addRow(new Object[]{p.getNombre(),p.getContenido(),p.getPrecio()});
        }
    }//GEN-LAST:event_jPanel_SalidaProductoComponentShown

    private void jTextField_ConsultaClientes_DiaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_ConsultaClientes_DiaKeyTyped
        char vchar=evt.getKeyChar();
        if(!(Character.isDigit(vchar))||(vchar==KeyEvent.VK_BACK_SPACE)||(vchar==KeyEvent.VK_DELETE))
            evt.consume();
    }//GEN-LAST:event_jTextField_ConsultaClientes_DiaKeyTyped

    private void jTextField_ConsultaClientes_MesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_ConsultaClientes_MesKeyTyped
        char vchar=evt.getKeyChar();
        if(!(Character.isDigit(vchar))||(vchar==KeyEvent.VK_BACK_SPACE)||(vchar==KeyEvent.VK_DELETE))
            evt.consume();
    }//GEN-LAST:event_jTextField_ConsultaClientes_MesKeyTyped

    private void jTextField_ConsultaClientes_AñoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_ConsultaClientes_AñoKeyTyped
        char vchar=evt.getKeyChar();
        if(!(Character.isDigit(vchar))||(vchar==KeyEvent.VK_BACK_SPACE)||(vchar==KeyEvent.VK_DELETE))
            evt.consume();
    }//GEN-LAST:event_jTextField_ConsultaClientes_AñoKeyTyped

    private void jTextField_SalidaProducto_NombreProductoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField_SalidaProducto_NombreProductoMouseClicked
        jTextField_SalidaProducto_NombreProducto.setText("");
    }//GEN-LAST:event_jTextField_SalidaProducto_NombreProductoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sis_Clientes_Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sis_Clientes_Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sis_Clientes_Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sis_Clientes_Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sis_Clientes_Clientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_AbrirMenuPrincipal;
    private javax.swing.JButton jButton_ConsultaClientes_Consultar;
    private javax.swing.JButton jButton_ConsultaClientes_LimpiarTabla;
    public static javax.swing.JButton jButton_RegistroClientes_Vender;
    private javax.swing.JButton jButton_SalidaProducto_LimpiarTodo;
    private javax.swing.JCheckBox jCheckBox_ConsultaClientes_Descendente;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel_ConsultaClientes;
    private javax.swing.JPanel jPanel_SalidaProducto;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable_ConsultaClientes;
    public static javax.swing.JTable jTable_RegistroClientes_Inventario;
    public static javax.swing.JTable jTable_SalidaProducto_Venta;
    private javax.swing.JTextField jTextField_ConsultaClientes_Año;
    private javax.swing.JTextField jTextField_ConsultaClientes_Dia;
    private javax.swing.JTextField jTextField_ConsultaClientes_Mes;
    public static javax.swing.JTextField jTextField_SalidaProducto_NombreProducto;
    public static javax.swing.JTextField jTextField_SalidaProducto_Total;
    // End of variables declaration//GEN-END:variables
}
