/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Sistema_de_gerencia;

import Clases.Cliente;
import Clases.Producto;
import static Menu.Menu_Principal.clientes;
import static Menu.Menu_Principal.productos;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.RowSorter;
import javax.swing.SortOrder;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author José Manuel Carrillo Torres
 */
public class Sis_Gerencia_Administracion_Gerencial extends javax.swing.JFrame {

    DefaultTableModel dfm_ConsultaClientes;
    /**
     * Creates new form FormAdministracionGerencial
     */
    public Sis_Gerencia_Administracion_Gerencial() {
        initComponents();
        this.setLocationRelativeTo(null);
        dfm_ConsultaClientes=(DefaultTableModel)jTable_ConsultaClientes.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable_ConsultaClientes = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jTextField_ConsultaClientes_Dia = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTextField_ConsultaClientes_Mes = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField_ConsultaClientes_Año = new javax.swing.JTextField();
        jCheckBox_ConsultaClientes_Descendente = new javax.swing.JCheckBox();
        jButton_ConsultaClientes_Consultar = new javax.swing.JButton();
        jButton_ConsultaClientes_LimpiarTabla = new javax.swing.JButton();
        jButton_AbrirMenuPrincipal = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Módulo de administración gerencial");

        jTable_ConsultaClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No. de cliente", "Producto", "Cantidad", "Importe"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable_ConsultaClientes.getTableHeader().setReorderingAllowed(false);
        jScrollPane4.setViewportView(jTable_ConsultaClientes);

        jLabel2.setText("Indique una fecha válida:");

        jTextField_ConsultaClientes_Dia.setText("DD");
        jTextField_ConsultaClientes_Dia.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField_ConsultaClientes_DiaFocusGained(evt);
            }
        });
        jTextField_ConsultaClientes_Dia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_ConsultaClientes_DiaKeyTyped(evt);
            }
        });

        jLabel1.setText("/");

        jTextField_ConsultaClientes_Mes.setText("MM");
        jTextField_ConsultaClientes_Mes.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField_ConsultaClientes_MesFocusGained(evt);
            }
        });
        jTextField_ConsultaClientes_Mes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_ConsultaClientes_MesKeyTyped(evt);
            }
        });

        jLabel3.setText("/");

        jTextField_ConsultaClientes_Año.setText("AAAA");
        jTextField_ConsultaClientes_Año.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField_ConsultaClientes_AñoFocusGained(evt);
            }
        });
        jTextField_ConsultaClientes_Año.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_ConsultaClientes_AñoKeyTyped(evt);
            }
        });

        jCheckBox_ConsultaClientes_Descendente.setText("Mostrar descendente");

        jButton_ConsultaClientes_Consultar.setText("Consultar");
        jButton_ConsultaClientes_Consultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ConsultaClientes_ConsultarActionPerformed(evt);
            }
        });

        jButton_ConsultaClientes_LimpiarTabla.setText("Limpiar tabla");
        jButton_ConsultaClientes_LimpiarTabla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ConsultaClientes_LimpiarTablaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 755, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_ConsultaClientes_Dia, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_ConsultaClientes_Mes, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_ConsultaClientes_Año, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jCheckBox_ConsultaClientes_Descendente)
                        .addGap(18, 18, 18)
                        .addComponent(jButton_ConsultaClientes_Consultar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_ConsultaClientes_LimpiarTabla)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField_ConsultaClientes_Dia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField_ConsultaClientes_Mes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField_ConsultaClientes_Año, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox_ConsultaClientes_Descendente)
                    .addComponent(jButton_ConsultaClientes_Consultar)
                    .addComponent(jButton_ConsultaClientes_LimpiarTabla))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 465, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Consulta de clientes", jPanel1);

        jButton_AbrirMenuPrincipal.setText("Abrir menú principal");
        jButton_AbrirMenuPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_AbrirMenuPrincipalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton_AbrirMenuPrincipal)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton_AbrirMenuPrincipal)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_AbrirMenuPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_AbrirMenuPrincipalActionPerformed
        Menu.Menu_Principal mi = new Menu.Menu_Principal();
        this.dispose();
        mi.setVisible(true);
    }//GEN-LAST:event_jButton_AbrirMenuPrincipalActionPerformed

    private void jTextField_ConsultaClientes_DiaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_ConsultaClientes_DiaFocusGained
        jTextField_ConsultaClientes_Dia.setText(null);
    }//GEN-LAST:event_jTextField_ConsultaClientes_DiaFocusGained

    private void jTextField_ConsultaClientes_MesFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_ConsultaClientes_MesFocusGained
        jTextField_ConsultaClientes_Mes.setText(null);
    }//GEN-LAST:event_jTextField_ConsultaClientes_MesFocusGained

    private void jTextField_ConsultaClientes_AñoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_ConsultaClientes_AñoFocusGained
        jTextField_ConsultaClientes_Año.setText(null);
    }//GEN-LAST:event_jTextField_ConsultaClientes_AñoFocusGained

    private void jButton_ConsultaClientes_ConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ConsultaClientes_ConsultarActionPerformed
                while(dfm_ConsultaClientes.getRowCount() > 0){dfm_ConsultaClientes.removeRow(0);}
        String dia=jTextField_ConsultaClientes_Dia.getText();
        if(dia.length()<2)
            dia="0"+dia;
        String mes=jTextField_ConsultaClientes_Mes.getText();
        if (mes.length()<2)
            mes="0"+mes;
        String fecha=dia+"/"+mes+"/"+jTextField_ConsultaClientes_Año.getText();
        for(Cliente c:clientes){
            if(c.getFecha().equals(fecha)){
                dfm_ConsultaClientes.addRow(new Object[]{c.getNumeroCliente(),null,c.getCantidad(),c.getImporte()});
                for(Producto p:productos){
                    if(p.getNumero()==c.getNumeroProducto())
                        dfm_ConsultaClientes.setValueAt(p.getNombre(),dfm_ConsultaClientes.getRowCount()-1,1);
                }
            }
        }
        if(jCheckBox_ConsultaClientes_Descendente.isSelected()){
            TableRowSorter<TableModel> sorter = new TableRowSorter<>(jTable_ConsultaClientes.getModel());             
            List<RowSorter.SortKey> sortKeys = new ArrayList<>();
            sortKeys.add(new RowSorter.SortKey(0, SortOrder.DESCENDING));
            sorter.setSortKeys(sortKeys);
            jTable_ConsultaClientes.setRowSorter(sorter);
        }
        else{
            TableRowSorter<TableModel> sorter = new TableRowSorter<>(jTable_ConsultaClientes.getModel());
            List<RowSorter.SortKey> sortKeys = new ArrayList<>();
            sortKeys.add(new RowSorter.SortKey(0, SortOrder.ASCENDING));
            sorter.setSortKeys(sortKeys);
            jTable_ConsultaClientes.setRowSorter(sorter);
        }
        if(jTable_ConsultaClientes.getRowCount()==0)
            JOptionPane.showMessageDialog(null, "No existen registros sobre esta fecha","Atención",JOptionPane.WARNING_MESSAGE); 
    }//GEN-LAST:event_jButton_ConsultaClientes_ConsultarActionPerformed

    private void jButton_ConsultaClientes_LimpiarTablaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ConsultaClientes_LimpiarTablaActionPerformed
        while(dfm_ConsultaClientes.getRowCount() > 0){dfm_ConsultaClientes.removeRow(0);}
    }//GEN-LAST:event_jButton_ConsultaClientes_LimpiarTablaActionPerformed

    private void jTextField_ConsultaClientes_DiaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_ConsultaClientes_DiaKeyTyped
        char vchar=evt.getKeyChar();
        if(!(Character.isDigit(vchar))||(vchar==KeyEvent.VK_BACK_SPACE)||(vchar==KeyEvent.VK_DELETE))
            evt.consume();
    }//GEN-LAST:event_jTextField_ConsultaClientes_DiaKeyTyped

    private void jTextField_ConsultaClientes_MesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_ConsultaClientes_MesKeyTyped
        char vchar=evt.getKeyChar();
        if(!(Character.isDigit(vchar))||(vchar==KeyEvent.VK_BACK_SPACE)||(vchar==KeyEvent.VK_DELETE))
            evt.consume();
    }//GEN-LAST:event_jTextField_ConsultaClientes_MesKeyTyped

    private void jTextField_ConsultaClientes_AñoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_ConsultaClientes_AñoKeyTyped
        char vchar=evt.getKeyChar();
        if(!(Character.isDigit(vchar))||(vchar==KeyEvent.VK_BACK_SPACE)||(vchar==KeyEvent.VK_DELETE))
            evt.consume();
    }//GEN-LAST:event_jTextField_ConsultaClientes_AñoKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sis_Gerencia_Administracion_Gerencial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sis_Gerencia_Administracion_Gerencial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sis_Gerencia_Administracion_Gerencial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sis_Gerencia_Administracion_Gerencial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sis_Gerencia_Administracion_Gerencial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_AbrirMenuPrincipal;
    private javax.swing.JButton jButton_ConsultaClientes_Consultar;
    private javax.swing.JButton jButton_ConsultaClientes_LimpiarTabla;
    private javax.swing.JCheckBox jCheckBox_ConsultaClientes_Descendente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable_ConsultaClientes;
    private javax.swing.JTextField jTextField_ConsultaClientes_Año;
    private javax.swing.JTextField jTextField_ConsultaClientes_Dia;
    private javax.swing.JTextField jTextField_ConsultaClientes_Mes;
    // End of variables declaration//GEN-END:variables
}
